version: "3"
services:
    postgres:
        container_name: postgres
        image: postgres:11-alpine
        volumes:
            - ./postgres/data:/var/lib/postgresql/data/pgdata
            - ./postgres/backups:/home/backups
        environment:
            - POSTGRES_USER=kaad
            - POSTGRES_PASSWORD=123456
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"

    api:
        container_name: api
        image: kaad/api:latest
        depends_on:
            - postgres
        links:
            - postgres:postgres
        volumes:
            - ./api/logs:/app/logs
            - ./api/gcloud:/app/gcloud
        environment:
            - NODE_ENV=production
            - PORT=3000
            - GLOBAL_PREFIX=api/v1
            - GLOBAL_URL=http://localhost
            - VALIDATION_LINK=24

            # Company Information
            - COMPANY_NAME=Hospitalitos de la Fe
            - COMPANY_URL=https://hospitalitosdelafe.org
            - COMPANY_LOGO_URL=https://nuevo.hospitalitosdelafe.org/wp-content/uploads/2022/12/Manual-de-Identidad-Hospitalitos-de-la-Fe-1-150x150.png

            # Security globals
            - ADMIN_ROLE=admin
            - USER_ROLE=user

            # Database
            - CONNECTION_TYPE=postgres
            - CONNECTION_HOST=postgres
            - CONNECTION_PORT=5432
            - CONNECTION_USERNAME=kaad
            - CONNECTION_PASSWORD=123456
            - CONNECTION_DATABASE=kaad_db
            - CONNECTION_AUTOLOAD_ENTITIES=true
            - CONNECTION_SYNCHRONIZE=true

            # JWT
            - JWT_ACCESS_TOKEN_SECRET=supersecretpassword
            - JWT_ACCESS_TOKEN_EXPIRATION_TIME=3000
            - JWT_REFRESH_TOKEN_SECRET=supersecretmegapower
            - JWT_REFRESH_TOKEN_EXPIRATION_TIME=3600
            - JWT_REFRESH_TOKEN_NAME=refresh_token

            # Mail Sender
            - MAIL_DEFAULT_FROM="Notificaciones Hospitalitos de la Fe" <no-reply@hospitalitosdelafe.org>
            - MAIL_TRANSPORT_HOST=smtp.gmail.com
            - MAIL_TRANSPORT_AUTH_USER=bernardo.pena.ramos@gmail.com
            - MAIL_TRANSPORT_AUTH_PASS=cefwrmzyskzrdbml

            # GCloud
            - GCLOUD_TOKEN_DIR=/app/gcloud/credentials
            - GCLOUD_TOKEN_FILE=youtube_upload_app_session.json
            - GCLOUD_CREDENTIAL_FILE=client_secret.json

            # MULTIMEDIA
            - MULTIMEDIA_ASSETS_PATH=../assets/multimedia
            - MULTIMEDIA_UPLOAD_PATH=../uploadedFiles
        ports:
            -  "3000:3000"

    backoffice:
        container_name: backoffice
        image: kaad/webapp/backoffice:latest
        environment:
            - PORT=443
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/ssl:/etc/ssl
        depends_on:
            - api
        ports:
            - "443:443"
            - "80:443"

networks:
    default:

